version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "medicine-inventory"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-4snxmjfk3eiq"
s3_prefix = "medicine-inventory"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
